version: '3.8'

services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app/
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/app_db
      - |
        ROCKET_DATABASES={
          postgres={url=postgres://postgres:postgres@postgres/app_db},
          redis={url=redis://redis:6379}  
        }
      - SMTP_HOST=smtp.mailtrap.io
      - SMTP_PORT=2525
      - SMTP_USERNAME=/run/secrets/mailtrap_username
      - SMTP_PASSWORD=/run/secrets/mailtrap_password
    secrets:
      - mailtrap_username
      - mailtrap_password
  
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    command: ["postgres", "-c", "log_statement=all"]  
  redis:
    image: redis:latest

secrets:
  mailtrap_username:
    file: ./secrets/mailtrap_username
  mailtrap_password:
    file: ./secrets/mailtrap_password